package com.ftl.tourisma.database;

import java.util.List;

public class Friends {
    public String Friend_Request_Id;
    public String Friend_User_Id;
    public String Friend_RequestDate;
    public String Friend_FriendUser_Id;
    public String Accepted;
    public String Friend_Id;
    public String Friend_FirstName;
    public String Friend_LastName;
    public String Friend_User_Name;
    public String Friend_Email;
    public String Friend_Mobile;
    public String Friend_Location;
    public String Friend_Latitude;
    public String Friend_Longitude;
    public String Friend_Facebook;
    public String Friend_Twitter;
    public String Friend_Gmail;
    public String Friend_Whatsapp;
    public String Friend_DP;
    public String Friend_Radius;
    public String Friend_DateJoin;
    public String Friend_Notification_Request;
    public String Friend_Notification_Arrival;
    public String Friend_Notification_GPS;
    public String Friend_DeviceToken;
    public String Friend_Device_Type;
    public String Friend_Badge_Count;
    public String Friend_Balance;
    public String Friend_Status;
    public String Friend_LastSeen;
    public String Friend_LastLocation;
    public String User_Id;
    public String User_FirstName;
    public String User_LastName;
    public String User_Name;
    public String User_Email;
    public String User_Mobile;
    public String User_Location;
    public String User_Latitude;
    public String User_Longitude;
    public String User_Facebook;
    public String User_Twitter;
    public String User_Gmail;
    public String User_Whatsapp;
    public String User_DP;
    public String User_Radius;
    public String User_DateJoin;
    public String User_Notification_Arrival;
    public String User_Notification_Request;
    public String User_Notification_GPS;
    public String User_Device_Token;
    public String User_Device_Type;
    public String User_Badge_Count;
    public String User_Balance;
    public String User_Status;
    public String User_LastSeen;
    public String User_LastLocation;
    public String dist;
    public String Friend_dist;
    public List<LastFootprint> LastFootprint;
}
